In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
df=pd.read_csv('E:\python practice\hate_speech_smalldataset.csv')

In [3]:
df.drop(columns=["Unnamed: 0","count","hate_speech","offensive_language","neither"],axis=1,inplace=True)

In [4]:
df.head()

class                                              tweet
0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [5]:
import re
import nltk
nltk.download('stopwords')


from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(df)):
    tweets = re.sub('[^-9A-Za-z]', ' ', df['tweet'][i])
    tweets = tweets.lower()
    tweets = tweets.split()
    
    tweets = [ps.stem(word) for word in tweets if not word in stopwords.words('english')]
    tweets = ' '.join(tweets)
    corpus.append(tweets)
print(corpus[0:10])  
df.head()

[nltk_data] Downloading package stopwords to C:\Users\Amjad Net
[nltk_data]     Cafe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['rt mayasolov woman complain clean hous amp man alway take trash', 'rt mleew boy dat cold tyga dwn bad cuffin dat hoe st place', 'rt urkindofbrand dawg rt sbabi life ever fuck bitch start cri confus shit', 'rt c g anderson viva base look like tranni', 'rt shenikarobert shit hear might true might faker bitch told ya', 'madison x shit blow claim faith somebodi still fuck hoe', 'brighterday sit hate anoth bitch got much shit go', 'selfiequeenbri caus tire big bitch come us skinni girl', 'amp might get ya bitch back amp that', 'rhythmixx hobbi includ fight mariam bitch']


class                                              tweet
0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
    
cv = CountVectorizer(max_features =5000,ngram_range=(1,2))
x=cv.fit_transform(corpus).toarray()
y=df['class']

In [7]:
import tensorflow as tf

In [8]:
tf.__version__

'2.3.0'

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [10]:
### Vocabulary size
voc_size=5000

In [14]:

onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr


[[2513, 382, 2299, 79, 1171, 4975, 162, 2848, 1775, 1104, 2302],
 [2513, 4701, 1984, 3562, 4054, 4980, 3647, 4413, 527, 3562, 486, 606, 3982],
 [2513, 3531, 3702, 2513, 1462, 1213, 1945, 267, 4171, 1231, 3582, 1046, 862],
 [2513, 2079, 1782, 798, 3630, 1269, 2617, 4449, 788],
 [2513, 2790, 862, 4557, 1368, 4628, 1368, 3863, 4171, 718, 2091],
 [2545, 1205, 862, 1554, 3909, 4127, 2297, 2622, 267, 486],
 [458, 4741, 1213, 1474, 4171, 363, 3612, 862, 469],
 [2471, 1439, 927, 4475, 4171, 2975, 4493, 4929, 4348],
 [162, 1368, 2613, 2091, 4171, 884, 162, 4875],
 [3974, 1281, 2755, 715, 2077, 4171],
 [2928, 4171, 4747, 250, 593, 3339, 4899, 4449, 1685],
 [4296, 730, 4171, 730, 1123],
 [486, 1706, 1760, 1752, 469, 3251],
 [4413, 4171, 2516, 4449],
 [4171, 2613],
 [4171, 841, 2300],
 [4171, 3977, 3572],
 [4171, 2449],
 [4171, 2613, 1263, 4853, 1952],
 [183, 4960, 162, 4413, 4171],
 [724, 4171, 3009, 885, 595],
 [538, 4171, 4449, 2512],
 [3009, 524, 486, 895, 4580],
 [267, 4171, 1308, 1068, 2994,

In [15]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1775 1104 2302]
 [   0    0    0 ...  486  606 3982]
 [   0    0    0 ... 3582 1046  862]
 ...
 [   0    0    0 ... 2154 4403 1761]
 [   0    0    0 ... 1096 3477 1827]
 [   0    0    0 ... 2229 1226 1660]]


In [16]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0, 2513,  382,
       2299,   79, 1171, 4975,  162, 2848, 1775, 1104, 2302])