In [19]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.text import Tokenizer

In [7]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
voc_size=10000

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2384, 3694, 5179, 3834], [2384, 3694, 5179, 5656], [2384, 8802, 5179, 4745], [8809, 3380, 888, 7390, 6258], [8809, 3380, 888, 7390, 3345], [6546, 2384, 316, 5179, 6932], [9438, 8415, 9805, 7390]]


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2384 3694 5179 3834]
 [   0    0    0    0 2384 3694 5179 5656]
 [   0    0    0    0 2384 8802 5179 4745]
 [   0    0    0 8809 3380  888 7390 6258]
 [   0    0    0 8809 3380  888 7390 3345]
 [   0    0    0 6546 2384  316 5179 6932]
 [   0    0    0    0 9438 8415 9805 7390]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:

print(model.predict(embedded_docs))

[[[-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615
    0.03050163  0.02788997  0.03208734  0.02593105 -0.01367806]
  [-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615
    0.03050163  0.02788997  0.03208734  0.02593105 -0.01367806]
  [-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615
    0.03050163  0.02788997  0.03208734  0.02593105 -0.01367806]
  [-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615
    0.03050163  0.02788997  0.03208734  0.02593105 -0.01367806]
  [ 0.00974853  0.04572355  0.00079902 -0.03461912 -0.00218097
   -0.00757189  0.04894212  0.00332775  0.0343779  -0.044193  ]
  [ 0.0372605   0.04280168  0.00706144  0.04563794  0.01018164
   -0.03216827 -0.00839515  0.02610477  0.01613953 -0.02090148]
  [ 0.02059339 -0.03929932  0.00118916 -0.0292635   0.04493052
    0.03654892 -0.01571038 -0.01860105  0.02901894 -0.04569234]
  [-0.03076384 -0.00246899  0.03073296 -0.02507393 -0.04815891
   -0.02111992  0.04485179  0.03247031  0.027042

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 2384, 3694, 5179, 3834])

In [17]:
print(model.predict(embedded_docs)[0])


[[-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615  0.03050163
   0.02788997  0.03208734  0.02593105 -0.01367806]
 [-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615  0.03050163
   0.02788997  0.03208734  0.02593105 -0.01367806]
 [-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615  0.03050163
   0.02788997  0.03208734  0.02593105 -0.01367806]
 [-0.04878075 -0.02168404 -0.00483472 -0.0416571   0.02744615  0.03050163
   0.02788997  0.03208734  0.02593105 -0.01367806]
 [ 0.00974853  0.04572355  0.00079902 -0.03461912 -0.00218097 -0.00757189
   0.04894212  0.00332775  0.0343779  -0.044193  ]
 [ 0.0372605   0.04280168  0.00706144  0.04563794  0.01018164 -0.03216827
  -0.00839515  0.02610477  0.01613953 -0.02090148]
 [ 0.02059339 -0.03929932  0.00118916 -0.0292635   0.04493052  0.03654892
  -0.01571038 -0.01860105  0.02901894 -0.04569234]
 [-0.03076384 -0.00246899  0.03073296 -0.02507393 -0.04815891 -0.02111992
   0.04485179  0.03247031  0.02704278 -0.04595668]]